export const PHRASES = [
  "Design is not just how it looks, but how it works: clean code is the key!",
  "Every line of code is a step toward a more user-friendly interface.",
  "Frontend is the art of turning complex ideas into simple experiences.",
  "Don't fear the error in your console; it's just the next step to success.",
  "Remember: the user doesn't see your code but feels your work.",
  "A great frontend engineer doesn't just write code but designs emotions.",
  "CSS might be challenging, but it's your tool to create visual magic.",
  "Animations are the language of frontend to tell stories.",
  "There's always a way to optimize your JavaScript—keep searching!",
  "Frontend is an art, and you are the artist.",
  "Every project is a new opportunity to innovate.",
  "HTML is the skeleton, CSS is the style, and JavaScript is the soul of the web.",
  "Success in frontend lies in the smallest details.",
  "Learning something new every day makes you a better developer.",
  "Don't be afraid to start from scratch; the best things often begin that way.",
  "Accessible interfaces are inclusive and powerful.",
  "True creativity in frontend comes when you work within constraints.",
  "Well-documented code is a gift to your future self.",
  "Fixing bugs makes you stronger and wiser.",
  "Every bug you fix is a lesson learned.",
  "It's not just code; it's an experience for the user.",
  "Frontend connects people with ideas.",
  "Your work has an impact, even if you don't always see it.",
  "Never underestimate the power of responsive design.",
  "Your code can change the world, one line at a time.",
  "Learning is a journey, not a destination.",
  "If it seems complicated, break it into smaller problems.",
  "There's always something new to learn in frontend—enjoy the ride!",
  "Consistent effort beats occasional talent.",
  "Your skills are valuable—never underestimate them.",
  "A great frontend engineer always thinks from the user's perspective.",
  "You don't need to be perfect, just better than yesterday.",
  "Building something from scratch is one of the greatest achievements.",
  "Patience is the key to solving complex problems.",
  "The beauty of code is as important as its functionality.",
  "A simple design is more powerful than a complex one.",
  "Small steps lead to big achievements.",
  "Believe in yourself and your ability to learn anything.",
  "Every mistake is an opportunity to grow.",
  "Collaboration makes projects shine.",
  "Your curiosity is your superpower as a developer.",
  "It's not just technology—it's creativity in action.",
  "Never stop experimenting with new ideas.",
  "Progress requires practice and persistence.",
  "Frontend isn't about tools; it's about solving problems.",
  "Never underestimate the power of a well-written line of code.",
  "Success comes from consistent practice.",
  "Don't compare yourself to others; compete with your past self.",
  "Design and development are two sides of the same coin.",
  "Your effort today will be tomorrow's success.",
  "Frontend is the bridge between creativity and functionality.",
  "The code you write today will shape the future of digital experiences.",
  "It's never too late to learn a new technology.",
  "Small improvements in user experience make a big difference.",
  "Continuous learning is the foundation of a great frontend engineer.",
  "Every pixel matters when it comes to frontend design.",
  "Challenges are opportunities in disguise.",
  "Don't fear refactoring; it improves both your code and your perspective.",
  "A good web design is one you don't have to explain.",
  "Building for accessibility means building for everyone.",
  "Frontend is more than technology; it's empathy for the user.",
  "Never stop questioning how to make your code better.",
  "A faster web is a happier web.",
  "Innovation starts with a simple question: How can I make this better?",
  "Write code as if the next developer is a beginner.",
  "Consistency is key to creating memorable experiences.",
  "Never underestimate the impact of a good variable name.",
  "Frontend requires both logic and intuition.",
  "Writing code is like writing poetry; every word counts.",
  "True creativity emerges when you work with limitations.",
  "Your attention to detail defines the quality of your work.",
  "A small change in your CSS can make a big difference.",
  "Never ignore the importance of testing.",
  "Clean code is like good design: it's easy to understand and maintain.",
  "The best part of frontend is that there's always something new to learn.",
  "Speed isn't everything, but it matters.",
  "Shared knowledge is multiplied knowledge.",
  "Never stop when you face an obstacle; there's always a solution.",
  "Building for the future means writing sustainable code.",
  "Intuitive design requires deep thinking.",
  "Mastering JavaScript comes from constant practice.",
  "Frontend not only connects pages but also people.",
  "Every project is a chance to leave your mark.",
  "Simplicity isn't lack of complexity; it's mastering it.",
  "If you can imagine it, you can build it on the web.",
  "There are no shortcuts to success, but there are for optimized code.",
  "The best ideas often come when you least expect them.",
  "Confidence in yourself is the best framework.",
  "Small details turn something good into something great.",
  "Every new project is a blank canvas for creativity.",
  "Frontend isn't just about tools; it's about purpose.",
  "Your energy and effort shape the quality of the final product.",
  "Learning how to learn is your most valuable skill.",
  "Mistakes are proof that you're trying.",
  "Never underestimate the impact of a good comment in your code.",
  "The best code is the one you never have to explain.",
  "Frontend is the living interaction between humans and machines.",
  "Don't be afraid to ask questions; it's the first step to knowledge.",
  "Motivation always beats talent without effort.",
  "Your dreams are achievable with persistence and constant learning.",
  "Great user experiences start with great frontend engineering.",
  "A good day starts with a clean console.",
  "Each bug you fix is a step closer to mastery.",
  "Frontend development is where creativity meets logic.",
  "Every line of code has the power to inspire and connect.",
  "Don't just code; craft experiences.",
  "The web is your canvas; JavaScript, CSS, and HTML are your brushes.",
  "User-first design always wins in the end.",
  "The best developers are always curious.",
  "A seamless UI is the result of countless iterations.",
  "Frontend is a journey of continuous improvement.",
  "The joy of solving a bug outweighs the frustration of finding it.",
  "Responsive design is about adapting to users, not just screens.",
  "The simplest solution is often the most elegant.",
  "Don't be afraid to delete and start over.",
  "Iteration is the secret to a polished product.",
  "The best designs are intuitive and invisible.",
  "Your work as a frontend engineer shapes how people experience the web.",
  "A small improvement today can make a big difference tomorrow.",
  "Strive to build things that are both functional and beautiful.",
  "Your attention to detail will set you apart as a developer.",
  "Success is the sum of small efforts repeated every day.",
  "Think like a user; code like a master.",
  "Frontend isn't about knowing everything; it's about being adaptable.",
  "Every website you build is a part of your legacy.",
  "Write code for humans, not just for machines.",
  "A user-friendly interface starts with empathy for the user.",
  "Your tools are powerful, but your vision is what drives innovation.",
  "Don't fear failure; it's the foundation of success.",
  "The best learning happens outside your comfort zone.",
  "Every problem is an opportunity to find a creative solution.",
  "Celebrate small wins; they lead to big victories.",
  "Never stop improving your skills; the web is always evolving.",
  "Your passion for frontend can create extraordinary things.",
  "A good frontend engineer never stops asking 'Why?'",
  "Even the simplest UI interactions can delight users.",
  "Quality always outweighs quantity in frontend development.",
  "A well-built website tells a story without words.",
  "Dream big, but focus small to achieve your goals.",
  "Consistency in design builds trust with users.",
  "A single line of code can make or break an experience.",
  "Remember, you're building for people, not just browsers.",
  "Every project you complete is a step toward greatness.",
  "Never underestimate the power of accessibility in your work.",
  "Debugging is an essential part of development, not a failure.",
  "Simplify complexity; that's the magic of frontend engineering.",
  "Your ability to learn quickly is your greatest asset.",
  "A great product starts with understanding your audience.",
  "Frontend is about bringing ideas to life in the browser.",
  "Your code isn't just functional; it's a part of something bigger.",
  "The power of frontend lies in creating seamless user experiences.",
  "Great developers never stop improving their craft.",
  "Every pixel tells a story; make sure it's a good one.",
  "Learning new frameworks is like unlocking new superpowers.",
  "Your patience with debugging shapes your success as a developer.",
  "A small animation can bring life to a static design.",
  "Your creativity is what makes frontend development exciting.",
  "Frontend is not just a skill; it's an art form.",
  "Every great website started as a simple idea.",
  "Your ability to adapt is your strength as a developer.",
  "Be proud of every small step forward in your learning journey.",
  "Writing maintainable code is a gift to your future self and your team.",
  "The best developers are always students of their craft.",
  "A responsive layout is a reflection of thoughtful design.",
  "Good UX is invisible; great UX is unforgettable.",
  "Frontend is about solving problems with elegance and simplicity.",
  "Don't just code features; build meaningful experiences.",
  "Your work as a developer creates tools that empower others.",
  "Never stop asking how you can make things better.",
  "Your passion for coding will lead you to extraordinary achievements.",
  "Write code that you're proud to show to others.",
  "Frontend engineers turn ideas into reality, one pixel at a time.",
  "Think outside the box, but don't forget the basics.",
  "Every CSS property is an opportunity for creativity.",
  "Celebrate every project you complete; it's a milestone.",
  "Your willingness to learn makes you unstoppable.",
  "Even a simple button can enhance a user's experience if done right.",
  "Greatness is built on the foundation of consistent effort.",
  "Good developers build code; great developers build experiences.",
  "Your mindset is the most important tool in your toolbox.",
  "Frontend development is about making technology human.",
  "Your attention to small details makes a big difference in the end.",
  "The best designs feel effortless because of your hard work.",
  "A growth mindset will take you further than talent alone.",
  "Every website you build is a reflection of your creativity.",
  "Think like a designer, code like an engineer.",
  "Your work has the power to inspire others.",
  "Keep pushing boundaries, but remember to enjoy the process.",
  "Don't fear making mistakes; they teach you the most valuable lessons.",
  "Every feature you build contributes to a better user experience.",
  "Be patient with your progress; mastery takes time.",
  "Always code as if you're writing for someone else.",
  "A single idea can transform the way people interact with the web.",
  "The best products come from collaboration and teamwork.",
  "Each project you complete is a stepping stone to something bigger.",
  "Frontend isn't just coding; it's storytelling through design.",
  "Your dedication today builds the foundation for future success.",
  "Empathy for the user is the cornerstone of great frontend development.",
  "Don't just meet expectations; exceed them.",
  "Every day you write code, you're improving as a developer.",
  "Frontend engineers have the power to create magic in the browser.",
  "Every challenge in frontend is an opportunity to grow.",
  "Your persistence will turn complex problems into simple solutions.",
  "Good code isn't written; it's rewritten.",
  "Every interaction you design impacts how people feel.",
  "The beauty of frontend is its blend of logic and creativity.",
  "A great frontend engineer knows the user comes first.",
  "Don't fear new technologies; embrace them with curiosity.",
  "The web is a constantly evolving playground—stay inspired.",
  "Celebrate progress, no matter how small it may seem.",
  "Every component you build is part of a larger story.",
  "Frontend engineering turns imagination into reality.",
  "Your ability to simplify complexity makes you a great developer.",
  "Coding is about learning to see possibilities where others see problems.",
  "The details you focus on today will shine in the final product.",
  "Never underestimate the impact of a great user experience.",
  "Frontend is about creating connections, not just pages.",
  "Every error in the console is a lesson waiting to be learned.",
  "Your work is the gateway to someone else's experience.",
  "Building accessible designs is building for everyone.",
  "The best developers are those who never stop learning.",
  "Your curiosity is your greatest ally in frontend development.",
  "The joy of seeing your work come to life is unmatched.",
  "Don't rush; great work takes time and focus.",
  "Your code has the power to inspire, educate, and entertain.",
  "The more you challenge yourself, the more you'll grow.",
  "Remember, you're not just coding; you're creating experiences.",
  "Think of every new project as a chance to innovate.",
  "Your determination to learn sets you apart from others.",
  "The web is limitless; so is your potential.",
  "Every small fix you make contributes to a better user experience.",
  "Celebrate the journey, not just the destination.",
  "Great developers solve problems before users even notice them.",
  "Your work as a frontend engineer shapes how people see the digital world.",
  "Embrace the process of learning; it will lead to mastery.",
  "The beauty of frontend lies in its ability to evolve.",
  "Don't be afraid to take risks in your designs.",
  "Every interaction matters; make it meaningful.",
  "Your ability to adapt will make you an exceptional developer.",
  "The best engineers know when to listen and learn.",
  "Keep experimenting; every idea is a stepping stone.",
  "Frontend engineering is about building trust through design.",
  "Don't just code for today; code for the future.",
  "Your work can turn an idea into a global solution.",
  "Great designs are born from collaboration and feedback.",
  "Every line of code contributes to the bigger picture.",
  "Your dedication is what transforms a good website into a great one.",
  "Stay humble, stay curious, and keep building.",
  "Frontend engineers have the power to make the internet a better place.",
  "The tools you use are important, but your vision is everything.",
  "Every success story starts with a single line of code.",
  "Believe in your ability to create amazing things.",
  "Every interaction you build is a chance to impress and inspire.",
  "Frontend development is where creativity meets functionality.",
  "Don't just aim for functionality; aim for delight.",
  "Your passion for frontend will take you further than any framework.",
  "The best solutions come from asking the right questions.",
  "Every skill you learn adds value to your work.",
  "Don't fear failure; it means you're pushing your limits.",
  "Great developers always keep the user in mind.",
  "Remember: every bug you solve improves the experience for someone else.",
  "Frontend engineering is about making the complex feel simple.",
  "You're not just writing code; you're crafting experiences.",
  "Your work can make someone's day better—don't underestimate that.",
  "Every new challenge is a step toward mastery.",
  "Good design is as important as good code.",
  "Your curiosity will lead you to solutions you never imagined.",
  "The best frontend engineers never stop learning.",
  "You're not just coding for today; you're coding for the future.",
  "Each project you complete makes you a better developer.",
  "Empathy for your users will always guide you in the right direction.",
  "Don't forget to enjoy the process of creation.",
  "A well-designed interface is the silent hero of the web.",
  "Your work connects people with information, ideas, and opportunities.",
  "Keep iterating; perfection comes from practice.",
  "The web is your playground—let your creativity shine.",
  "Collaboration makes good projects great.",
  "Your code isn't just for browsers; it's for people.",
  "Every improvement you make creates a better experience for someone.",
  "Celebrate the small wins—they lead to big achievements.",
  "Your persistence will turn obstacles into opportunities.",
  "Think of every bug as a puzzle waiting to be solved.",
  "Frontend isn't just a job; it's a way to make a difference.",
  "Always strive for clean, readable, and maintainable code.",
  "The best developers embrace both logic and creativity.",
  "Every project you complete is a milestone in your journey.",
  "Your ability to adapt will define your success in frontend development.",
  "Don't be afraid to experiment; innovation starts with trying new things.",
  "Every detail you focus on improves the overall experience.",
  "Remember, you're creating for users, not just yourself.",
  "A great frontend engineer knows that testing is key to success.",
  "Your passion for learning will keep you ahead of the curve.",
  "Every website you build is a chance to make a positive impact.",
  "The web is full of possibilities—explore them with curiosity.",
  "A simple design is often the most effective.",
  "Your code has the potential to reach millions of people.",
  "Every challenge is an opportunity to grow your skills.",
  "Great frontend development starts with understanding your users.",
  "Your dedication to quality will set you apart as a developer.",
  "Remember, the best products are built with teamwork.",
  "Keep pushing yourself to learn and grow every day.",
  "Frontend engineering is about making technology feel human.",
  "Your creativity will turn ideas into incredible experiences.",
  "Celebrate progress, even if it feels small.",
  "Every feature you build enhances someone's interaction with the web.",
  "The best designs come from understanding the user's needs.",
  "Never stop exploring the boundaries of what's possible in frontend.",
  "Your work has the power to make the web more inclusive.",
  "Keep refining your skills; every bit of effort counts.",
  "The most memorable websites are the simplest ones.",
  "You're not just a developer; you're a creator of experiences.",
  "Stay curious, stay passionate, and keep building amazing things.",
  "A good developer writes code; a great one solves problems.",
  "Your attention to detail makes the difference between good and great.",
  "Great engineers never stop asking, 'How can this be better?'",
  "Each day you code is a step closer to your goals.",
  "Frontend engineering is about turning vision into reality.",
  "Don't just write code; write something you're proud of.",
  "The web evolves every day, and so should you.",
  "Every bug you solve is a reminder of how far you've come.",
  "Your work inspires others to explore, learn, and create.",
  "Stay persistent, stay curious, and keep building for the web.",
];
